return {
    Order = {"Bloom", "Glimmer", "Nova"},
    Bloom = {damage = 21, headMultiplier = 1.6, interval = 0.12, magazine = 26, reload = 1.8, range = 300, spread = 1.1, pellets = 1, recoil = 0.6, color = Color3.fromRGB(255, 110, 195), role = "ASSAULT"},
    Glimmer = {damage = 11, headMultiplier = 1.3, interval = 0.8, magazine = 7, reload = 2.3, range = 100, spread = 5, pellets = 7, recoil = 2.1, color = Color3.fromRGB(110, 230, 255), role = "SCATTER"},
    Nova = {damage = 64, headMultiplier = 1.8, interval = 1.0, magazine = 5, reload = 2.5, range = 450, spread = 0.3, pellets = 1, recoil = 2.7, color = Color3.fromRGB(210, 160, 255), role = "PRECISION"},
}
